### ISSUE TITLE
Better error messages for missing keys in the settings.ini file

### ISSUE THREAD

**Issue by caillou** [camarel/raspifon#11]
On a recent update, a `CameraDeviceIndex` was intorduced in the `settings.ini` file. The following is how I was greeted, this might be a bit confusing to non-programming users:

```
python3 raspifon.py
Traceback (most recent call last):
  File "raspifon.py", line 163, in <module>
    snapshot = Snapshot(config['DEFAULT']['CameraDeviceIndex'])
  File "/usr/lib/python3.5/configparser.py", line 1230, in getitem
    raise KeyError(key)
KeyError: 'CameraDeviceIndex'
```

**Comment by caillou** [comment]
If we go for an interactive setup assistant, we could tell the users that they can fix the error by re-running the setup assistant.
